replicaCount: 1
image:
  repository: juangomeper/monolito-inventario
  tag: "1.0.44-dev-f2bf182"   
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 3000
resources:
  requests:
    memory: "256Mi"
    cpu: "50m"
  limits:
    memory: "512Mi"
    cpu: "200m"
ingress:
  enabled: true
  className: nginx
  path: /patrones-dev(/|$)(.*)   
postgres:
  image: postgres:15
  storage: 512Mi
  user: postgres
  password: ArrozConMollejas
  db: pedidosdb_dev   
  port: 5432
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
