replicaCount: 2
image:
  repository: juangomeper/monolito-inventario
  tag: "1.0.22-fa01652"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 3000
resources:
  requests:
    memory: "512Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "400m"
ingress:
  enabled: true
  className: nginx
  path: /patrones(/|$)(.*)
postgres:
  image: postgres:15
  storage: 1Gi
  user: postgres
  password: ArrozConMollejas
  db: pedidosdb
  port: 5432
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 85

