apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patrones
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: monolito=juangomeper/monolito-inventario
    argocd-image-updater.argoproj.io/monolito.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: none
    argocd-image-updater.argoproj.io/monolito.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/monolito.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://juangomeper.github.io/helm-chart/  
    chart: patrones                                      # <-- Nombre del chart
    targetRevision: 0.1.0                                # <-- Versión del chart (de Chart.yaml)
    helm:
      values: |
        replicaCount: 2
        image:
          repository: juangomeper/monolito-inventario
          tag: "1.0.2"
          pullPolicy: IfNotPresent
        service:
          port: 80
          targetPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        ingress:
          enabled: true
          className: nginx
          path: /patrones(/|$)(.*)
        postgres:
          image: postgres:15
          storage: 1Gi
          user: postgres
          password: ArrozConMollejas
          db: pedidosdb
          port: 5432
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
