apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patrones-dev
  namespace: argocd
spec:
  destination:
    namespace: patrones-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://juangomeper.github.io/helm-chart/
    chart: patrones
    targetRevision: '*'
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
